seed: 0
deterministic: false

checkpoint_config:
  interval: 1
  max_keep_ckpts: 1

log_config:
  interval: 10
  hooks:
    -
      type: TextLoggerHook
    # -
    #   type: TensorboardLoggerHook
    -
      type: WandbLoggerHook
      init_kwargs: 
        project: BEVFUSION_v01
        name: 'user_name'

load_from: null
resume_from: null

cudnn_benchmark: false
fp16:
  loss_scale: 
    growth_interval: 2000

max_epochs: 20
runner:
  type: CustomEpochBasedRunner
  max_epochs: ${max_epochs}
